### ISSUE TITLE
Update gravity spheres

### ISSUE THREAD

**Issue by MtuMartian** [MtuMartian/HGD-Team6-2016#15]
We should discuss how we want the gravity spheres to look and create a new sprite for them.

**Comment by mplecapt** [comment]
Gravity spheres consist of (at the moment) an interior, exterior, and an atmosphere. The interior is currently a particle effect, while the exterior (which needs to updated yet) will be a sort of glass lattice structure, and the atmosphere will most likely be some particle effect, but the general idea is a 'glow' around the planet.
